plugins {
    id 'java'
}

group = 'com.onex01'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    // Альтернативный репозиторий с прекомпилированными версиями Mindustry
    maven { url 'https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository' }
}

ext {
    mindustryVersion = 'v145'
}

dependencies {
    compileOnly "com.github.Anuken.Mindustry:core:$mindustryVersion"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

// Задача для Desktop
jar {
    archiveFileName = "cloud-save-mod.jar"
    
    from(rootProject.file("mod.hjson")) {
        into ""
    }
    
    from("bundles") {
        into "bundles"
    }
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    
    manifest {
        attributes 'Implementation-Title': archiveFileName,
                   'Implementation-Version': archiveVersion
    }
}

// Задача для Android (deploy)
task deploy(type: Jar, dependsOn: jar) {
    archiveFileName = "cloud-save-mod-android.jar"
    
    from sourceSets.main.output
    
    from(rootProject.file("mod.hjson")) {
        into ""
    }
    
    from("bundles") {
        into "bundles"
    }
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}